/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedAutoresponderRouteImport } from './routes/_authenticated/autoresponder'
import { Route as AuthenticatedAutomationIndexRouteImport } from './routes/_authenticated/automation/index'
import { Route as AuthenticatedAutomationWorkflowsNewRouteImport } from './routes/_authenticated/automation/workflows.new'
import { Route as AuthenticatedAutomationWorkflowsIdRouteImport } from './routes/_authenticated/automation/workflows.$id'
import { Route as AuthenticatedAutomationMessagesIdRouteImport } from './routes/_authenticated/automation/messages.$id'
import { Route as AuthenticatedAutomationMessagesIdDesignRouteImport } from './routes/_authenticated/automation/messages.$id.design'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoresponderRoute =
  AuthenticatedAutoresponderRouteImport.update({
    id: '/autoresponder',
    path: '/autoresponder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationIndexRoute =
  AuthenticatedAutomationIndexRouteImport.update({
    id: '/automation/',
    path: '/automation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationWorkflowsNewRoute =
  AuthenticatedAutomationWorkflowsNewRouteImport.update({
    id: '/automation/workflows/new',
    path: '/automation/workflows/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationWorkflowsIdRoute =
  AuthenticatedAutomationWorkflowsIdRouteImport.update({
    id: '/automation/workflows/$id',
    path: '/automation/workflows/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationMessagesIdRoute =
  AuthenticatedAutomationMessagesIdRouteImport.update({
    id: '/automation/messages/$id',
    path: '/automation/messages/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationMessagesIdDesignRoute =
  AuthenticatedAutomationMessagesIdDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedAutomationMessagesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/autoresponder': typeof AuthenticatedAutoresponderRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/automation/': typeof AuthenticatedAutomationIndexRoute
  '/automation/messages/$id': typeof AuthenticatedAutomationMessagesIdRouteWithChildren
  '/automation/workflows/$id': typeof AuthenticatedAutomationWorkflowsIdRoute
  '/automation/workflows/new': typeof AuthenticatedAutomationWorkflowsNewRoute
  '/automation/messages/$id/design': typeof AuthenticatedAutomationMessagesIdDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/autoresponder': typeof AuthenticatedAutoresponderRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/automation': typeof AuthenticatedAutomationIndexRoute
  '/automation/messages/$id': typeof AuthenticatedAutomationMessagesIdRouteWithChildren
  '/automation/workflows/$id': typeof AuthenticatedAutomationWorkflowsIdRoute
  '/automation/workflows/new': typeof AuthenticatedAutomationWorkflowsNewRoute
  '/automation/messages/$id/design': typeof AuthenticatedAutomationMessagesIdDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/autoresponder': typeof AuthenticatedAutoresponderRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/automation/': typeof AuthenticatedAutomationIndexRoute
  '/_authenticated/automation/messages/$id': typeof AuthenticatedAutomationMessagesIdRouteWithChildren
  '/_authenticated/automation/workflows/$id': typeof AuthenticatedAutomationWorkflowsIdRoute
  '/_authenticated/automation/workflows/new': typeof AuthenticatedAutomationWorkflowsNewRoute
  '/_authenticated/automation/messages/$id/design': typeof AuthenticatedAutomationMessagesIdDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/autoresponder'
    | '/contacts'
    | '/dashboard'
    | '/reports'
    | '/automation/'
    | '/automation/messages/$id'
    | '/automation/workflows/$id'
    | '/automation/workflows/new'
    | '/automation/messages/$id/design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/autoresponder'
    | '/contacts'
    | '/dashboard'
    | '/reports'
    | '/automation'
    | '/automation/messages/$id'
    | '/automation/workflows/$id'
    | '/automation/workflows/new'
    | '/automation/messages/$id/design'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/autoresponder'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/automation/'
    | '/_authenticated/automation/messages/$id'
    | '/_authenticated/automation/workflows/$id'
    | '/_authenticated/automation/workflows/new'
    | '/_authenticated/automation/messages/$id/design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autoresponder': {
      id: '/_authenticated/autoresponder'
      path: '/autoresponder'
      fullPath: '/autoresponder'
      preLoaderRoute: typeof AuthenticatedAutoresponderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/': {
      id: '/_authenticated/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AuthenticatedAutomationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/workflows/new': {
      id: '/_authenticated/automation/workflows/new'
      path: '/automation/workflows/new'
      fullPath: '/automation/workflows/new'
      preLoaderRoute: typeof AuthenticatedAutomationWorkflowsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/workflows/$id': {
      id: '/_authenticated/automation/workflows/$id'
      path: '/automation/workflows/$id'
      fullPath: '/automation/workflows/$id'
      preLoaderRoute: typeof AuthenticatedAutomationWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/messages/$id': {
      id: '/_authenticated/automation/messages/$id'
      path: '/automation/messages/$id'
      fullPath: '/automation/messages/$id'
      preLoaderRoute: typeof AuthenticatedAutomationMessagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/messages/$id/design': {
      id: '/_authenticated/automation/messages/$id/design'
      path: '/design'
      fullPath: '/automation/messages/$id/design'
      preLoaderRoute: typeof AuthenticatedAutomationMessagesIdDesignRouteImport
      parentRoute: typeof AuthenticatedAutomationMessagesIdRoute
    }
  }
}

interface AuthenticatedAutomationMessagesIdRouteChildren {
  AuthenticatedAutomationMessagesIdDesignRoute: typeof AuthenticatedAutomationMessagesIdDesignRoute
}

const AuthenticatedAutomationMessagesIdRouteChildren: AuthenticatedAutomationMessagesIdRouteChildren =
  {
    AuthenticatedAutomationMessagesIdDesignRoute:
      AuthenticatedAutomationMessagesIdDesignRoute,
  }

const AuthenticatedAutomationMessagesIdRouteWithChildren =
  AuthenticatedAutomationMessagesIdRoute._addFileChildren(
    AuthenticatedAutomationMessagesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutoresponderRoute: typeof AuthenticatedAutoresponderRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedAutomationIndexRoute: typeof AuthenticatedAutomationIndexRoute
  AuthenticatedAutomationMessagesIdRoute: typeof AuthenticatedAutomationMessagesIdRouteWithChildren
  AuthenticatedAutomationWorkflowsIdRoute: typeof AuthenticatedAutomationWorkflowsIdRoute
  AuthenticatedAutomationWorkflowsNewRoute: typeof AuthenticatedAutomationWorkflowsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutoresponderRoute: AuthenticatedAutoresponderRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedAutomationIndexRoute: AuthenticatedAutomationIndexRoute,
  AuthenticatedAutomationMessagesIdRoute:
    AuthenticatedAutomationMessagesIdRouteWithChildren,
  AuthenticatedAutomationWorkflowsIdRoute:
    AuthenticatedAutomationWorkflowsIdRoute,
  AuthenticatedAutomationWorkflowsNewRoute:
    AuthenticatedAutomationWorkflowsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
