/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfirmSenderRouteImport } from './routes/confirm-sender'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedEmailsAndDomainsRouteImport } from './routes/_authenticated/emails-and-domains'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedAutoresponderIndexRouteImport } from './routes/_authenticated/autoresponder/index'
import { Route as AuthenticatedAutomationIndexRouteImport } from './routes/_authenticated/automation/index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AuthenticatedAutomationWorkflowsNewRouteImport } from './routes/_authenticated/automation/workflows.new'
import { Route as AuthenticatedAutomationWorkflowsIdRouteImport } from './routes/_authenticated/automation/workflows.$id'
import { Route as AuthenticatedAutomationMessagesIdIndexRouteImport } from './routes/_authenticated/automation/messages.$id.index'
import { Route as AuthenticatedAutomationMessagesIdDesignRouteImport } from './routes/_authenticated/automation/messages.$id.design'
import { Route as AuthenticatedAutomationMessagesIdBuilderRouteImport } from './routes/_authenticated/automation/messages.$id.builder'

const ConfirmSenderRoute = ConfirmSenderRouteImport.update({
  id: '/confirm-sender',
  path: '/confirm-sender',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsAndDomainsRoute =
  AuthenticatedEmailsAndDomainsRouteImport.update({
    id: '/emails-and-domains',
    path: '/emails-and-domains',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoresponderIndexRoute =
  AuthenticatedAutoresponderIndexRouteImport.update({
    id: '/autoresponder/',
    path: '/autoresponder/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationIndexRoute =
  AuthenticatedAutomationIndexRouteImport.update({
    id: '/automation/',
    path: '/automation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAutomationWorkflowsNewRoute =
  AuthenticatedAutomationWorkflowsNewRouteImport.update({
    id: '/automation/workflows/new',
    path: '/automation/workflows/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationWorkflowsIdRoute =
  AuthenticatedAutomationWorkflowsIdRouteImport.update({
    id: '/automation/workflows/$id',
    path: '/automation/workflows/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationMessagesIdIndexRoute =
  AuthenticatedAutomationMessagesIdIndexRouteImport.update({
    id: '/automation/messages/$id/',
    path: '/automation/messages/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationMessagesIdDesignRoute =
  AuthenticatedAutomationMessagesIdDesignRouteImport.update({
    id: '/automation/messages/$id/design',
    path: '/automation/messages/$id/design',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationMessagesIdBuilderRoute =
  AuthenticatedAutomationMessagesIdBuilderRouteImport.update({
    id: '/automation/messages/$id/builder',
    path: '/automation/messages/$id/builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirm-sender': typeof ConfirmSenderRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emails-and-domains': typeof AuthenticatedEmailsAndDomainsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/automation/': typeof AuthenticatedAutomationIndexRoute
  '/autoresponder/': typeof AuthenticatedAutoresponderIndexRoute
  '/automation/workflows/$id': typeof AuthenticatedAutomationWorkflowsIdRoute
  '/automation/workflows/new': typeof AuthenticatedAutomationWorkflowsNewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/automation/messages/$id/builder': typeof AuthenticatedAutomationMessagesIdBuilderRoute
  '/automation/messages/$id/design': typeof AuthenticatedAutomationMessagesIdDesignRoute
  '/automation/messages/$id/': typeof AuthenticatedAutomationMessagesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confirm-sender': typeof ConfirmSenderRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emails-and-domains': typeof AuthenticatedEmailsAndDomainsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/automation': typeof AuthenticatedAutomationIndexRoute
  '/autoresponder': typeof AuthenticatedAutoresponderIndexRoute
  '/automation/workflows/$id': typeof AuthenticatedAutomationWorkflowsIdRoute
  '/automation/workflows/new': typeof AuthenticatedAutomationWorkflowsNewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/automation/messages/$id/builder': typeof AuthenticatedAutomationMessagesIdBuilderRoute
  '/automation/messages/$id/design': typeof AuthenticatedAutomationMessagesIdDesignRoute
  '/automation/messages/$id': typeof AuthenticatedAutomationMessagesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confirm-sender': typeof ConfirmSenderRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emails-and-domains': typeof AuthenticatedEmailsAndDomainsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/automation/': typeof AuthenticatedAutomationIndexRoute
  '/_authenticated/autoresponder/': typeof AuthenticatedAutoresponderIndexRoute
  '/_authenticated/automation/workflows/$id': typeof AuthenticatedAutomationWorkflowsIdRoute
  '/_authenticated/automation/workflows/new': typeof AuthenticatedAutomationWorkflowsNewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/automation/messages/$id/builder': typeof AuthenticatedAutomationMessagesIdBuilderRoute
  '/_authenticated/automation/messages/$id/design': typeof AuthenticatedAutomationMessagesIdDesignRoute
  '/_authenticated/automation/messages/$id/': typeof AuthenticatedAutomationMessagesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confirm-sender'
    | '/contacts'
    | '/dashboard'
    | '/emails-and-domains'
    | '/reports'
    | '/automation/'
    | '/autoresponder/'
    | '/automation/workflows/$id'
    | '/automation/workflows/new'
    | '/lovable/email/transactional/preview'
    | '/automation/messages/$id/builder'
    | '/automation/messages/$id/design'
    | '/automation/messages/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confirm-sender'
    | '/contacts'
    | '/dashboard'
    | '/emails-and-domains'
    | '/reports'
    | '/automation'
    | '/autoresponder'
    | '/automation/workflows/$id'
    | '/automation/workflows/new'
    | '/lovable/email/transactional/preview'
    | '/automation/messages/$id/builder'
    | '/automation/messages/$id/design'
    | '/automation/messages/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confirm-sender'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/emails-and-domains'
    | '/_authenticated/reports'
    | '/_authenticated/automation/'
    | '/_authenticated/autoresponder/'
    | '/_authenticated/automation/workflows/$id'
    | '/_authenticated/automation/workflows/new'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/automation/messages/$id/builder'
    | '/_authenticated/automation/messages/$id/design'
    | '/_authenticated/automation/messages/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfirmSenderRoute: typeof ConfirmSenderRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confirm-sender': {
      id: '/confirm-sender'
      path: '/confirm-sender'
      fullPath: '/confirm-sender'
      preLoaderRoute: typeof ConfirmSenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails-and-domains': {
      id: '/_authenticated/emails-and-domains'
      path: '/emails-and-domains'
      fullPath: '/emails-and-domains'
      preLoaderRoute: typeof AuthenticatedEmailsAndDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autoresponder/': {
      id: '/_authenticated/autoresponder/'
      path: '/autoresponder'
      fullPath: '/autoresponder/'
      preLoaderRoute: typeof AuthenticatedAutoresponderIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/': {
      id: '/_authenticated/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AuthenticatedAutomationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/automation/workflows/new': {
      id: '/_authenticated/automation/workflows/new'
      path: '/automation/workflows/new'
      fullPath: '/automation/workflows/new'
      preLoaderRoute: typeof AuthenticatedAutomationWorkflowsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/workflows/$id': {
      id: '/_authenticated/automation/workflows/$id'
      path: '/automation/workflows/$id'
      fullPath: '/automation/workflows/$id'
      preLoaderRoute: typeof AuthenticatedAutomationWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/messages/$id/': {
      id: '/_authenticated/automation/messages/$id/'
      path: '/automation/messages/$id'
      fullPath: '/automation/messages/$id/'
      preLoaderRoute: typeof AuthenticatedAutomationMessagesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/messages/$id/design': {
      id: '/_authenticated/automation/messages/$id/design'
      path: '/automation/messages/$id/design'
      fullPath: '/automation/messages/$id/design'
      preLoaderRoute: typeof AuthenticatedAutomationMessagesIdDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/messages/$id/builder': {
      id: '/_authenticated/automation/messages/$id/builder'
      path: '/automation/messages/$id/builder'
      fullPath: '/automation/messages/$id/builder'
      preLoaderRoute: typeof AuthenticatedAutomationMessagesIdBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailsAndDomainsRoute: typeof AuthenticatedEmailsAndDomainsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedAutomationIndexRoute: typeof AuthenticatedAutomationIndexRoute
  AuthenticatedAutoresponderIndexRoute: typeof AuthenticatedAutoresponderIndexRoute
  AuthenticatedAutomationWorkflowsIdRoute: typeof AuthenticatedAutomationWorkflowsIdRoute
  AuthenticatedAutomationWorkflowsNewRoute: typeof AuthenticatedAutomationWorkflowsNewRoute
  AuthenticatedAutomationMessagesIdBuilderRoute: typeof AuthenticatedAutomationMessagesIdBuilderRoute
  AuthenticatedAutomationMessagesIdDesignRoute: typeof AuthenticatedAutomationMessagesIdDesignRoute
  AuthenticatedAutomationMessagesIdIndexRoute: typeof AuthenticatedAutomationMessagesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailsAndDomainsRoute: AuthenticatedEmailsAndDomainsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedAutomationIndexRoute: AuthenticatedAutomationIndexRoute,
  AuthenticatedAutoresponderIndexRoute: AuthenticatedAutoresponderIndexRoute,
  AuthenticatedAutomationWorkflowsIdRoute:
    AuthenticatedAutomationWorkflowsIdRoute,
  AuthenticatedAutomationWorkflowsNewRoute:
    AuthenticatedAutomationWorkflowsNewRoute,
  AuthenticatedAutomationMessagesIdBuilderRoute:
    AuthenticatedAutomationMessagesIdBuilderRoute,
  AuthenticatedAutomationMessagesIdDesignRoute:
    AuthenticatedAutomationMessagesIdDesignRoute,
  AuthenticatedAutomationMessagesIdIndexRoute:
    AuthenticatedAutomationMessagesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfirmSenderRoute: ConfirmSenderRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
